CREATE TABLE runs (
	run_id VARCHAR NOT NULL, 
	batch_id VARCHAR NOT NULL, 
	created_at DATETIME NOT NULL, 
	finished_at DATETIME, 
	run_kind VARCHAR NOT NULL, 
	repeat_idx INTEGER NOT NULL, 
	target_id VARCHAR NOT NULL, 
	model_id VARCHAR NOT NULL, 
	response_model VARCHAR, 
	harness VARCHAR NOT NULL, 
	harness_version VARCHAR NOT NULL, 
	defense_config VARCHAR NOT NULL, 
	carrier_task_id VARCHAR, 
	benign_query_id VARCHAR, 
	payload_id VARCHAR, 
	technique VARCHAR, 
	goal VARCHAR, 
	channel VARCHAR, 
	attacker_mode VARCHAR, 
	lang VARCHAR, 
	obfuscation VARCHAR, 
	run_canaries VARCHAR NOT NULL, 
	delivered BOOLEAN, 
	g1_hit BOOLEAN NOT NULL, 
	g1_channel VARCHAR, 
	g2_hit BOOLEAN NOT NULL, 
	g2_severity VARCHAR, 
	g3_hit BOOLEAN NOT NULL, 
	loop_flag BOOLEAN NOT NULL, 
	blocked_by VARCHAR, 
	outcome VARCHAR, 
	parse_error BOOLEAN NOT NULL, 
	parse_error_reason VARCHAR, 
	judge_pass BOOLEAN, 
	hard_fact_pass BOOLEAN, 
	keyword_check_pass BOOLEAN, 
	tcp FLOAT, 
	final_answer TEXT, 
	n_steps INTEGER NOT NULL, 
	tokens_in INTEGER NOT NULL, 
	tokens_out INTEGER NOT NULL, 
	latency_ms INTEGER NOT NULL, 
	PRIMARY KEY (run_id), 
	CONSTRAINT ck_run_kind CHECK (run_kind IN ('attack', 'benign')), 
	CONSTRAINT ck_target_id CHECK (target_id IN ('A1', 'A2', 'A3')), 
	CONSTRAINT ck_harness CHECK (harness IN ('none', 'HN-CC', 'HN-OW')), 
	CONSTRAINT ck_attacker CHECK ((attacker_mode IS NULL OR attacker_mode IN ('blind', 'adaptive'))), 
	CONSTRAINT ck_technique CHECK ((technique IS NULL OR technique IN ('T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'))), 
	CONSTRAINT ck_goal CHECK ((goal IS NULL OR goal IN ('G1', 'G2', 'G3'))), 
	CONSTRAINT ck_channel CHECK ((channel IS NULL OR channel IN ('K1', 'K2a', 'K2b'))), 
	CONSTRAINT ck_g1_channel CHECK ((g1_channel IS NULL OR g1_channel IN ('http', 'email', 'ticket', 'answer'))), 
	CONSTRAINT ck_g2_severity CHECK ((g2_severity IS NULL OR g2_severity IN ('read_only', 'internal_write', 'external_action'))), 
	CONSTRAINT ck_blocked_by CHECK ((blocked_by IS NULL OR blocked_by IN ('defense', 'model_refusal', 'harness'))), 
	CONSTRAINT ck_outcome CHECK ((outcome IS NULL OR outcome IN ('success', 'failed', 'blocked', 'pass', 'fail'))), 
	CONSTRAINT ck_blocked_needs_cause CHECK (outcome IS NULL OR outcome <> 'blocked' OR blocked_by IS NOT NULL), 
	CONSTRAINT ck_attack_labels CHECK (run_kind <> 'attack' OR (technique IS NOT NULL AND goal IS NOT NULL AND channel IS NOT NULL AND attacker_mode IS NOT NULL)), 
	CONSTRAINT ck_g1_channel_on_hit CHECK (g1_hit = 0 OR g1_channel IS NOT NULL)
);

CREATE INDEX ix_runs_batch_id ON runs (batch_id);

CREATE INDEX ix_runs_cell ON runs (batch_id, target_id, technique, channel, goal);

CREATE TABLE steps (
	id INTEGER NOT NULL, 
	run_id VARCHAR NOT NULL, 
	step_idx INTEGER NOT NULL, 
	created_at DATETIME NOT NULL, 
	kind VARCHAR NOT NULL, 
	llm_text TEXT, 
	tool_name VARCHAR, 
	tool_args TEXT, 
	tool_result TEXT, 
	defense_hits VARCHAR NOT NULL, 
	tokens_in INTEGER, 
	tokens_out INTEGER, 
	latency_ms INTEGER, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_step_kind CHECK (kind IN ('llm', 'tool', 'defense')), 
	FOREIGN KEY(run_id) REFERENCES runs (run_id)
);

CREATE INDEX ix_steps_run_id ON steps (run_id);
